version: '3'

services:
  jenkins:
    build: ../
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - ../config/casc.yaml:/var/jenkins_home/casc.yaml

volumes:
  jenkins_home: