# docker-compose.yaml de ejemplo
# ----------------------------------------------------------------------------------------
# El archivo de configuración casc.yaml está montado, si es editado mientras el contenedor
# está activo accede a: 
# -> http://localhost:8080/manage/configuration-as-code/
# y clicka en "Reload Existing Configuration" para que los cambios se apliquen
# ----------------------------------------------------------------------------------------
version: '3'

services:
  jenkins:
    build: ../jenkins/
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_data:/var/jenkins_home
      - ../jenkins/config/casc.yaml:/var/jenkins_home/casc.yaml
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://localhost:30080'; gitlab_rails['gitlab_shell_ssh_port']=30022;"
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    ports:
      - 30080:30080
      - 30022:22
    volumes:
      - gitlab_data:/var/opt/gitlab
      - ./gitlab_data:/var/opt/gitlab

volumes:
  jenkins_home:
  gitlab_data: